
export const ActionTypes = {
    SET_LANGUAGE: "SET_LANGUAGE",
    ALLOW_ALL_COOKIES: "ALLOW_ALL_COOKIES",
    ALLOW_SELECTED_COOKIES: "ALLOW_SELECTED_COOKIES", 
    SHOW_SETTINGS: "SHOW_SETTINGS" 
};